#!/usr/bin/env python

import os
from src.index import handler
import boto3


def getjson():
    dynamodb_client = boto3.client('dynamodb')
    payload = dynamodb_client.get_item(
        TableName=table_name(),
        Key={
            'request_id': {
                'S': str(request_id())
            }
        }
    )
    return payload['Item']['data']['S']

def update_dynamodb_response(json_string):
    dynamodb_client = boto3.client('dynamodb')
    dynamodb_client.update_item(
        TableName=table_name(),
        Key={
            'request_id': {
                'S': str(request_id())
            }
        },
        UpdateExpression="SET json_result = :r",
        ExpressionAttributeValues={
            ':r': {
                'S': json_string
            }
        },
        ReturnValues="UPDATED_NEW"
    )

def model():
    return os.getenv('MODEL') or 'prophet'

def request_id():
    return os.getenv('REQUEST_ID')

def table_name():
    return os.getenv('TABLE_NAME')


json_string = getjson()
prediction = handler(json_string, model())
update_dynamodb_response(prediction)
print('Farcaster completed')
